# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

params =  
{ :user =>
    {
	    :email => 'johnthomasraphael@gmail.com',
	    :password => 'pass1234',
	    :password_confirmation => 'pass1234',
	    :admin => true,
	    :approved => true,
  	}
}
User.create!(params[:user])

uploader = ImageUploader.new
my_file = File.open(File.join(Rails.root, '/app/assets/images/upseal.png'))
uploader.store!(my_file)

uploader = ImageUploader.new
my_file = File.open(File.join(Rails.root, '/app/assets/images/up_baguio.jpg'))
uploader.store!(my_file)
params =  
{ :university =>
	{
		:univ_name => 'UP Baguio',
		:image => File.open(File.join(Rails.root, '/app/assets/images/up_baguio.jpg')),
		:university_profiles_attributes => 
		[
			{
			    :classification => 'Campus Site',
				:description => 'Lot 1, Baguio City Campus(Main)',
				:owner => 'UPB',
				:total_area_hectare => '3.0494',
				:total_area_meter => '30494',
				:acquisition => 'Proclamation No. 807, approved dated Dec. 18, 1961',
				:titling_status => 'P-3107',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Currently being utilized by the Main Campus',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot 3, Baguio City Campus(Near the lot of the Archbishop of Manila)',
				:owner => 'UPB',
				:total_area_hectare => '0.4887',
				:total_area_meter => '4887',
				:acquisition => 'Proclamation No. 352 approved dated March 31, 2004 with Special Patent No. 3658 dated June 23, 2004',
				:titling_status => 'P-3107',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Fenced off by the Archbishop of Manila Property',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Residential',
				:description => 'Lot A PSD-131102-001883, UP Baguio (near Walk-Up Appt.)',
				:owner => 'UPB',
				:total_area_hectare => '0.3298',
				:total_area_meter => '3298',
				:acquisition => 'Deed of Donation by GSIS in Mar. 23, 1992',
				:titling_status => 'T-58228',
				:date_issued => DateTime.new(1993,2,4),
				:tax_dec_no => '',
				:remarks => 'Currently being utilized for faculty/staff use.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Residential',
				:description => 'Lot B PSD-131102-001883, UP Baguio Residence Hall',
				:owner => 'UPB',
				:total_area_hectare => '0.9802',
				:total_area_meter => '9802',
				:acquisition => 'Deed of Donation by GSIS in Mar. 23, 1993',
				:titling_status => 'T-58229',
				:date_issued => DateTime.new(1993,2,4),
				:tax_dec_no => '',
				:remarks => 'Occupied by 17 family squatters and under court litigation for the correction of the technical description of the title.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot 3A2, SWO-40968, UP Baguio Campus (near Department of Tourism), Governor Pack Road, Baguio City',
				:owner => 'UPB',
				:total_area_hectare => '0.2132',
				:total_area_meter => '2132',
				:acquisition => 'Per DENR records, Lots 3A1 to 3 are UP properties',
				:titling_status => 'Untitled',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Planned to be transformed into eco-park.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Research',
				:description => 'Sabkil, Itogon, Benguet',
				:owner => 'UPB',
				:total_area_hectare => '2.0047',
				:total_area_meter => '20047',
				:acquisition => 'Deed of Absolute Sale dated Sept. 25, 1963',
				:titling_status => 'T-1964',
				:date_issued => DateTime.new(1963,10,25),
				:tax_dec_no => '',
				:remarks => 'Planted with trees and planned to be developed by the College of Science',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Research',
				:description => 'Sabkil, Itogon, Benguet',
				:owner => 'UPB',
				:total_area_hectare => '1.9044',
				:total_area_meter => '19044',
				:acquisition => 'Deed of Absolute Sale dated Sept. 25, 1963',
				:titling_status => 'T-1965',
				:date_issued => DateTime.new(1963,10,25),
				:tax_dec_no => '',
				:remarks => 'Planted with trees and planned to be developed by the College of Science',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
		]
	}
}
University.create!(params[:university])

uploader = ImageUploader.new
my_file = File.open(File.join(Rails.root, '/app/assets/images/up_cebu.jpg'))
uploader.store!(my_file)
params =  
{ :university =>
	{
		:univ_name => 'UP Cebu',
		:image => File.open(File.join(Rails.root, '/app/assets/images/up_cebu.jpg')),
		:university_profiles_attributes => 
		[
			{
			    :classification => 'Residential, Campus Site',
				:description => 'Lot 911-B-2-A, PSD-3582, Lahug, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '5.0002',
				:total_area_meter => '50002',
				:acquisition => 'Donated by the Province of Cebu',
				:titling_status => 'T-31155',
				:date_issued => DateTime.new(1965,1,12),
				:tax_dec_no => 'GRC6-03-022-05073',
				:remarks => 'About 25,000 sq. mts. Are occupied by informal settlers the rest is where the College campus is occupying with buildings.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Residential',
				:description => 'Lot 911-B-2-B, PSD-3582, Lahug, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '1.3805',
				:total_area_meter => '13805',
				:acquisition => 'Donated by the Province of Cebu',
				:titling_status => 'T-31156',
				:date_issued => DateTime.new(1965,1,12),
				:tax_dec_no => 'GRC6-04-023-06233',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Residential, Campus Site',
				:description => 'Lot 911-B-2-C-2-E , PSD-28978, Lahug, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '2.617',
				:total_area_meter => '26170',
				:acquisition => 'Donated by the Province of Cebu',
				:titling_status => 'T-31166',
				:date_issued => DateTime.new(1965,1,12),
				:tax_dec_no => 'GRC6-03-022-04999',
				:remarks => 'About 18,000 sq. mts. Of the area are occupied by informal settlers the rest is where the Undergraduate Building stands.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Residential',
				:description => 'Lot 911-B-2-C-2-A , PSD-28978, Lahug, Cebu ',
				:owner => 'UP Cebu',
				:total_area_hectare => '0.1312',
				:total_area_meter => '1312',
				:acquisition => 'Donated by the Province of Cebu',
				:titling_status => 'T-31164',
				:date_issued => DateTime.new(1965,1,12),
				:tax_dec_no => 'GRC6-03-022-05139',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Residential, Campus Site',
				:description => 'Lot 911-B-2-C-2-B, PSD-28978, Lahug, Cebu ',
				:owner => 'UP Cebu',
				:total_area_hectare => '4.879',
				:total_area_meter => '48790',
				:acquisition => 'Donated by the Province of Cebu',
				:titling_status => 'T-31165',
				:date_issued => DateTime.new(1965,1,12),
				:tax_dec_no => '',
				:remarks => 'This is where the Arts & Sciences Bldg., the Cebu Cultural Center, and UP High School are situated.  The sides, roughly about 5,000 sq. mts. are occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3115, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '0.2839',
				:total_area_meter => '2839',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36878',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3116, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '0.1386',
				:total_area_meter => '1386',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36879',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3117, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '0.5645',
				:total_area_meter => '5645',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36880',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3118, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '0.1249',
				:total_area_meter => '1249',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36881',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3119, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '1.2262',
				:total_area_meter => '12262',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36882',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3120, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '0.4369',
				:total_area_meter => '4369',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36883',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3121, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '0.745',
				:total_area_meter => '7450',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36884',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3122, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '0.0221',
				:total_area_meter => '221',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36885',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3123, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '0.2183',
				:total_area_meter => '2183',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36886',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3124, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '1.4533',
				:total_area_meter => '14533',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36887',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3125, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '0.7491',
				:total_area_meter => '7491',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36888',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3126-B, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '1.0844',
				:total_area_meter => '10844',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36893',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3127, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '0.1214',
				:total_area_meter => '1214',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36889',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3128, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '0.2467',
				:total_area_meter => '2467',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36890',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3195, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '1.1972',
				:total_area_meter => '11972',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36891',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Stewardship',
				:description => 'Lot 3196-B, Lawaan, Talisay, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '0.7875',
				:total_area_meter => '7875',
				:acquisition => 'Donated by C.J. Yulo and Sons Inc.',
				:titling_status => 'T-36892',
				:date_issued => DateTime.new(1975,9,1),
				:tax_dec_no => '',
				:remarks => 'The entire area is occupied by informal settlers.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Campus Site',
				:description => 'Lot 1-G, South Road Properties, Cebu',
				:owner => 'UP Cebu',
				:total_area_hectare => '5.1372',
				:total_area_meter => '51372',
				:acquisition => 'Donated by the City of Cebu Local Government',
				:titling_status => 'T-107-2011000061   PT-15974',
				:date_issued => DateTime.new(2010,10,19),
				:tax_dec_no => '',
				:remarks => 'The site for UP Cebu Professional Schools whereby construction of the 1st building structure is on-going.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
		]
	}
}
University.create!(params[:university])

uploader = ImageUploader.new
my_file = File.open(File.join(Rails.root, '/app/assets/images/up_diliman.jpg'))
uploader.store!(my_file)
params =  
{ :university =>
	{
		:univ_name => 'UP Diliman',
		:image => File.open(File.join(Rails.root, '/app/assets/images/up_diliman.jpg')),
		:university_profiles_attributes => 
		[
			{
			    :classification => 'Campus Site',
				:description => 'Diliman, Quezon City',
				:owner => 'UP Diliman',
				:total_area_hectare => '4.5489',
				:total_area_meter => '45489',
				:acquisition => '',
				:titling_status => 'RT-58561',
				:date_issued => DateTime.new(1975,10,2),
				:tax_dec_no => '',
				:remarks => 'Deed of Sale between National Government and UP dated March 1, 1949. UP shall devote to specific public uses in connection with administration of UP.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Campus Site',
				:description => 'Diliman, Quezon City',
				:owner => 'UP Diliman',
				:total_area_hectare => '1.19842',
				:total_area_meter => '11984.2',
				:acquisition => '',
				:titling_status => 'RT-57991',
				:date_issued => DateTime.new(1975,10,2),
				:tax_dec_no => '',
				:remarks => 'Deed of Sale between National Government and UP dated March 1, 1949. UP shall devote to specific public uses in connection with administration of UP.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Campus Site',
				:description => 'Diliman, Quezon City',
				:owner => 'UP Diliman',
				:total_area_hectare => '128.6285',
				:total_area_meter => '1286285',
				:acquisition => '',
				:titling_status => 'RT-27912',
				:date_issued => DateTime.new(1973,8,15),
				:tax_dec_no => '',
				:remarks => 'Deed of Sale between National Government and UP dated March 1, 1949. UP shall devote to specific public uses in connection with administration of UP.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Campus Site',
				:description => 'Diliman, Quezon City',
				:owner => 'UP Diliman',
				:total_area_hectare => '134.36371',
				:total_area_meter => '1343637.1',
				:acquisition => '',
				:titling_status => 'RT-58201',
				:date_issued => DateTime.new(1973,8,15),
				:tax_dec_no => '',
				:remarks => 'Deed of Sale between National Government and UP dated March 1, 1949. UP shall devote to specific public uses in connection with administration of UP.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Campus Site',
				:description => 'Diliman, Quezon City',
				:owner => 'UP Diliman',
				:total_area_hectare => '66.2815',
				:total_area_meter => '662815',
				:acquisition => '',
				:titling_status => 'RT-57411',
				:date_issued => DateTime.new(1973,8,15),
				:tax_dec_no => '',
				:remarks => 'Deed of Sale between National Government and UP dated March 1, 1949. UP shall devote to specific public uses in connection with administration of UP.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Campus Site',
				:description => 'Diliman, Quezon City',
				:owner => 'UP Diliman',
				:total_area_hectare => '114.8609',
				:total_area_meter => '1148609',
				:acquisition => '',
				:titling_status => 'RT-107350',
				:date_issued => DateTime.new(1973,8,15),
				:tax_dec_no => '',
				:remarks => 'Deed of Sale between National Government and UP dated March 1, 1949. UP shall devote to specific public uses in connection with administration of UP.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Campus Site',
				:description => 'Diliman, Quezon City',
				:owner => 'UP Diliman',
				:total_area_hectare => '43.2171',
				:total_area_meter => '432171',
				:acquisition => '',
				:titling_status => 'RT-57197',
				:date_issued => DateTime.new(1973,8,15),
				:tax_dec_no => '',
				:remarks => 'Deed of Sale between National Government and UP dated March 1, 1949. UP shall devote to specific public uses in connection with administration of UP.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Extension',
				:description => 'Bolinao, Pangasinan (Marine Science Institute)',
				:owner => 'UP Diliman',
				:total_area_hectare => '4.97',
				:total_area_meter => '50033',
				:acquisition => '',
				:titling_status => 'RT-10564',
				:date_issued => DateTime.new(1989,11,10),
				:tax_dec_no => '',
				:remarks => 'Donated by the Municipality of Bolinao, Pangasinan dated July 5, 1988.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Extension',
				:description => 'UP Extension Program Pampanga, Clark Special Economic Zone, Pampanga',
				:owner => 'UP Diliman',
				:total_area_hectare => '3.33',
				:total_area_meter => '33300',
				:acquisition => 'The UP Extension Program Pampanga site still owned by CDC.',
				:titling_status => '',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Extension',
				:description => '8131 Manila Ave. Subcom Area, Subic Bay Freeport Zone, Olongapo',
				:owner => 'UP Diliman',
				:total_area_hectare => '0.05',
				:total_area_meter => '500',
				:acquisition => '',
				:titling_status => '',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
			    :classification => 'Marine Biological Station',
				:description => 'Poblacion, Puerto Galera, Oriental Mindoro',
				:owner => 'UP Diliman',
				:total_area_hectare => '0.2626',
				:total_area_meter => '2626',
				:acquisition => '',
				:titling_status => '',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
		]
	}
}
University.create!(params[:university])


uploader = ImageUploader.new
my_file = File.open(File.join(Rails.root, '/app/assets/images/up_LB.jpg'))
uploader.store!(my_file)
params =  
{ :university =>
	{
		:univ_name => 'UP Los Banos',
		:image => File.open(File.join(Rails.root, '/app/assets/images/up_LB.jpg')),
		:university_profiles_attributes => 
		[
			{
			    :classification => 'Campus Site',
				:description => 'Lot-2, Plan 1-698, Maahas, Los Banos, Laguna',
				:owner => 'UP',
				:total_area_hectare => '11.10',
				:total_area_meter => '111000',
				:acquisition => '',
				:titling_status => 'OCT-718',
				:date_issued => DateTime.new(1960,4,22),
				:tax_dec_no => '7963',
				:remarks => 'UPLB Farm',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot-3, Plan 1-698, Maahas, Los Banos, Laguna',
				:owner => 'UP',
				:total_area_hectare => '26.53',
				:total_area_meter => '265303',
				:acquisition => '',
				:titling_status => 'OCT-718',
				:date_issued => DateTime.new(1960,4,22),
				:tax_dec_no => '7963',
				:remarks => 'IRRI Leased Area',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot A-2-D, PSD-25736, Portion of Lot A-2, PSD-24950, Maahas, Los Banos, Laguna',
				:owner => 'UP',
				:total_area_hectare => '13.78',
				:total_area_meter => '137816',
				:acquisition => '',
				:titling_status => 'TCT-18691',
				:date_issued => DateTime.new(1960,11,4),
				:tax_dec_no => '008-2588',
				:remarks => 'IRRI Leased Area',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Consolidation of Lots C2A3, C2B1, C2B3, C2A2A, C2A2B, Maahas, Los Banos, Laguna',
				:owner => 'UPS',
				:total_area_hectare => '101.91',
				:total_area_meter => '1019107',
				:acquisition => '',
				:titling_status => 'TCT-45712',
				:date_issued => DateTime.new(1975,11,11),
				:tax_dec_no => '',
				:remarks => 'IRRI Leased Area',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot D1B (LRC) PSD-227910, C2A3, C2B1, C2B2, C2B3, C2A2A, C2A2B, Tuntungin, Los Banos, Laguna',
				:owner => 'UPS',
				:total_area_hectare => '70.00',
				:total_area_meter => '699998',
				:acquisition => '',
				:titling_status => 'TCT-45714',
				:date_issued => DateTime.new(1975,12,16),
				:tax_dec_no => '014-2038',
				:remarks => 'PEZA Zone',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot 2 of Consolidation Plan, PSD-19293 Portion of Consolidation of Lots B2A, Lot B2B, etc. Mainit, Paciano Rizal, Bay Laguna',
				:owner => 'UPS',
				:total_area_hectare => '79.59',
				:total_area_meter => '795861',
				:acquisition => '',
				:titling_status => 'TCT-45716',
				:date_issued => DateTime.new(1975,12,14),
				:tax_dec_no => '99-02-008-00646',
				:remarks => 'IRRI Leased Area less 10 hectares resettlement site and private properties',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Boundary of Consolidation Plan (LRC) PCN-256 Portion of Con Lots D2C1 to D2C2, Tuntungin-Putho, Los Banos, Laguna',
				:owner => 'UPS',
				:total_area_hectare => '24.58',
				:total_area_meter => '245833',
				:acquisition => '',
				:titling_status => 'TCT-45981',
				:date_issued => DateTime.new(1975,12,16),
				:tax_dec_no => '014-2040',
				:remarks => 'PEZA Zone',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Block 10 PSD-04-038016 location of UP Rural High School & IPB Farm, Paciano Rizal, Bay Laguna',
				:owner => 'UP',
				:total_area_hectare => '11.89',
				:total_area_meter => '118907',
				:acquisition => '',
				:titling_status => 'TCT-201222',
				:date_issued => DateTime.new(1990,1,2),
				:tax_dec_no => '99-02-008-00688',
				:remarks => 'Remaining portion after deducting a 10 hectares resettlement site ',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot 8 of Plan SWO-4894-AMD, Paciano Rizal, Bay , Laguna',
				:owner => 'UP',
				:total_area_hectare => '13.49',
				:total_area_meter => '134897',
				:acquisition => '',
				:titling_status => 'TCT-58488',
				:date_issued => DateTime.new(1978,6,23),
				:tax_dec_no => '99-02-008-00652',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot C2D1 PSD-78900, Portion of Lot C2D, PSD-2495, Paciano Rizal, Bay, Laguna',
				:owner => 'UP',
				:total_area_hectare => '22.73',
				:total_area_meter => '227347',
				:acquisition => '',
				:titling_status => 'TCT-61520',
				:date_issued => DateTime.new(1979,2,19),
				:tax_dec_no => '99-02-008-00638',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot C2D2 PSD-78900, Portion of Lot C2D, PSD-2498, Paciano Rizal, Bay, Laguna',
				:owner => 'UP',
				:total_area_hectare => '22.73',
				:total_area_meter => '227347',
				:acquisition => '',
				:titling_status => 'TCT-59105',
				:date_issued => DateTime.new(1978,8,9),
				:tax_dec_no => '99-02-008-00639',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot C2D3 PSD-78900, Portion of Lot C2D, PSD-24950, Pacaino, Rizal, Bay, Laguna',
				:owner => 'UP',
				:total_area_hectare => '22.73',
				:total_area_meter => '227347',
				:acquisition => '',
				:titling_status => 'TCT-58693',
				:date_issued => DateTime.new(1978,7,14),
				:tax_dec_no => '99-02-008-00640',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot C2D4 PSD-78900, Portion of Lot C2D, PSD-24950,  Paciano Rizal, Bay, Laguna',
				:owner => 'UPS',
				:total_area_hectare => '22.73',
				:total_area_meter => '227347',
				:acquisition => '',
				:titling_status => 'TCT-60349',
				:date_issued => DateTime.new(1978,10,25),
				:tax_dec_no => '99-02-008-00641',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot C2C2 PSD-23846, Portion of Lot C2C, Paciano Rizal, Bay, Laguna',
				:owner => 'UPS',
				:total_area_hectare => '5.00',
				:total_area_meter => '50000',
				:acquisition => '',
				:titling_status => 'TCT-62824',
				:date_issued => DateTime.new(1979,6,4),
				:tax_dec_no => '99-02-008-00630',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot C2C3 PSD-23846, Portion of Lot C2C, Paciano Rizal, Bay, Laguna',
				:owner => 'UPS',
				:total_area_hectare => '5.00',
				:total_area_meter => '50000',
				:acquisition => '',
				:titling_status => 'TCT-62825',
				:date_issued => DateTime.new(1979,6,4),
				:tax_dec_no => '990-02-008-00631',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot C2C4 PSD-23846, Portion of Lot C2c, PSD-24950, Mainit, Paciano Rizal, Bay, Laguna',
				:owner => 'UPS',
				:total_area_hectare => '5.50',
				:total_area_meter => '55000',
				:acquisition => '',
				:titling_status => 'TCT-62826',
				:date_issued => DateTime.new(1979,6,4),
				:tax_dec_no => '99-02-008-00632',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot C2C6 PSD-23846, Portion of Lot C2C, PSD-24950, Mainit, Paciano Rizal, Bay, Laguna',
				:owner => 'UPS',
				:total_area_hectare => '6.00',
				:total_area_meter => '60003',
				:acquisition => '',
				:titling_status => 'TCT-62827',
				:date_issued => DateTime.new(1979,6,4),
				:tax_dec_no => '99-02-008-00634',
				:remarks => 'PEZA Zone',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot C2C7 PSD-23846, Portion of Lot C2C, PSD-24950, Paciano Rizal, Bay, Laguna',
				:owner => 'UPS',
				:total_area_hectare => '5.50',
				:total_area_meter => '55000',
				:acquisition => '',
				:titling_status => 'TCT-62828',
				:date_issued => DateTime.new(1979,6,4),
				:tax_dec_no => '99-02-008-00635',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot C2C8 PSD-23846, Portion of Lot C2C, Paciano Rizal, Bay, Laguna',
				:owner => 'UPS',
				:total_area_hectare => '5.00',
				:total_area_meter => '50000',
				:acquisition => '',
				:titling_status => 'TCT-62829',
				:date_issued => DateTime.new(1979,6,4),
				:tax_dec_no => '99-02-008-00633',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot C2C5 PSD-23846, Portion of Lot C2C, Paciano Rizal, Bay, Laguna',
				:owner => 'UPS',
				:total_area_hectare => '6.00',
				:total_area_meter => '60003',
				:acquisition => '',
				:titling_status => 'TCT-62830',
				:date_issued => DateTime.new(1979,6,4),
				:tax_dec_no => '99-02-008-00633',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot C2C9 PSD-23846, Portion of Lot C2C, Paciano Rizal, Bay, Laguna',
				:owner => 'UPS',
				:total_area_hectare => '5.00',
				:total_area_meter => '50000',
				:acquisition => '',
				:titling_status => 'TCT-62831',
				:date_issued => DateTime.new(1979,6,4),
				:tax_dec_no => '99-02-008-00637',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot C2D1, (LRC), PSD-23846, Portion of Lot C2C, PSD-24950, Paciano Rizal, Bay, Laguna',
				:owner => 'UPS',
				:total_area_hectare => '43.00',
				:total_area_meter => '430006',
				:acquisition => '',
				:titling_status => 'TCT-65137',
				:date_issued => DateTime.new(1979,9,29),
				:tax_dec_no => '99-02-008-00629',
				:remarks => '',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot A2A, PSD-25736, Portion of Lot A2, PSD-24950, Maahas, Los Banos, Laguna',
				:owner => 'UP',
				:total_area_hectare => '0.09',
				:total_area_meter => '900',
				:acquisition => '',
				:titling_status => 'TCT-18688',
				:date_issued => DateTime.new(1960,11,4),
				:tax_dec_no => '008-2548',
				:remarks => 'IRRI Leased Area',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot A2B, PSD-25736, Portion of Lot A2, PSD-24950.  Maahas, Los Banos, Laguna',
				:owner => 'UP',
				:total_area_hectare => '0.09',
				:total_area_meter => '900',
				:acquisition => '',
				:titling_status => 'TCT-18689',
				:date_issued => DateTime.new(1960,11,4),
				:tax_dec_no => '008-2549',
				:remarks => 'IRRI Leased Area',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot A2C, PSD-25736, Maahas, Los Banos, Laguna',
				:owner => 'UP',
				:total_area_hectare => '0.09',
				:total_area_meter => '900',
				:acquisition => '',
				:titling_status => 'TCT-18690',
				:date_issued => DateTime.new(1960,11,4),
				:tax_dec_no => '008-2550',
				:remarks => 'IRRI Leased Area',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot C2A1A (LCR), PSD-59070, Portion of Lot C2A1 PSD-48386, Paciano Rizal, Bay Laguna ',
				:owner => 'UPS',
				:total_area_hectare => '2.99',
				:total_area_meter => '29881',
				:acquisition => '',
				:titling_status => 'TCT-38999',
				:date_issued => DateTime.new(1974,9,6),
				:tax_dec_no => '99-02-008-00625',
				:remarks => '30,881 sqm on title',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot-3 PSD-04003202, Portion of Lot A-2, PSD-24950, Batong Malake, Los Banos',
				:owner => 'UPLB',
				:total_area_hectare => '0.45',
				:total_area_meter => '4536',
				:acquisition => '',
				:titling_status => 'TCT-259067',
				:date_issued => DateTime.new(1992,11,16),
				:tax_dec_no => '005-4206',
				:remarks => 'Area was replaced by UPLBFI property in Jubiileeb.  UCMA UPL-UPLB donation.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Road Lots',
				:description => 'Lot 1A2 PSD-04021154 (Road to IPB-formerly owned by Col. Maligalig)',
				:owner => 'UPLB',
				:total_area_hectare => '0.04',
				:total_area_meter => '431',
				:acquisition => '',
				:titling_status => 'TCT-294523',
				:date_issued => DateTime.new(1994,3,28),
				:tax_dec_no => '26150',
				:remarks => 'IPB Road',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'IRRI Housing Area',
				:description => 'Lot II, Block II, PSD-134832 Portion of Lot B2D, Tuntungin, Los Banos, Laguna',
				:owner => 'UPLB',
				:total_area_hectare => '0.02',
				:total_area_meter => '240',
				:acquisition => '',
				:titling_status => 'TCT-51568',
				:date_issued => DateTime.new(1977,3,17),
				:tax_dec_no => '014-0211',
				:remarks => 'Leased to IRRI',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'IRRI Housing Area',
				:description => 'Lot 5, Block II, PSD-134832 Portion of Lot B2D, Tuntungin, Los Banos, Laguna',
				:owner => 'UPLB',
				:total_area_hectare => '0.02',
				:total_area_meter => '240',
				:acquisition => '',
				:titling_status => 'TCT-51603',
				:date_issued => DateTime.new(1977,3,22),
				:tax_dec_no => '014-0215',
				:remarks => 'Leased to IRRI',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'IRRI Housing Area',
				:description => 'Lot 7, Block II, PSD-134832 Portion of Lot B2D, PSD-45211, Tuntungin, Los Banos, Laguna',
				:owner => 'UPLB',
				:total_area_hectare => '0.02',
				:total_area_meter => '240',
				:acquisition => '',
				:titling_status => 'TCT-51604',
				:date_issued => DateTime.new(1977,3,22),
				:tax_dec_no => '014-0214',
				:remarks => 'Leased to IRRI',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'IRRI Housing Area',
				:description => 'Lot 8, Block II, PSD-134832 Portion of Lot B2D, PSD-45211, Tuntungin, Los Banos Laguna',
				:owner => 'UPLB',
				:total_area_hectare => '0.02',
				:total_area_meter => '240',
				:acquisition => '',
				:titling_status => 'TCT-51605',
				:date_issued => DateTime.new(1977,3,22),
				:tax_dec_no => '014-0212',
				:remarks => 'Leased to IRRI',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'IRRI Housing Area',
				:description => 'Lot 5, Block II, PSD-134832 Portion of Lot BD2D, PSD-45211, Tuntungin, Los Banos, Laguna',
				:owner => 'UPLB',
				:total_area_hectare => '0.02',
				:total_area_meter => '240',
				:acquisition => '',
				:titling_status => 'TCT-51683',
				:date_issued => DateTime.new(1977,3,29),
				:tax_dec_no => '014-0216',
				:remarks => 'Leased to IRRI',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'IRRI Housing Area',
				:description => 'Lot 13, Block II, PSD-134833 Portion of Lot B2D, PSD-48211, Tuntungin, Los Banos, Laguna',
				:owner => 'UPLB',
				:total_area_hectare => '0.02',
				:total_area_meter => '240',
				:acquisition => '',
				:titling_status => 'TCT-51684',
				:date_issued => DateTime.new(1977,3,29),
				:tax_dec_no => '014-0210',
				:remarks => 'Leased to IRRI',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
		]
	}
}
University.create!(params[:university])


#start here
uploader = ImageUploader.new
my_file = File.open(File.join(Rails.root, '/app/assets/images/up_manila.jpg'))
uploader.store!(my_file)
params =  
{ :university =>
	{
		:univ_name => 'UP Baguio',
		:image => File.open(File.join(Rails.root, '/app/assets/images/up_baguio.jpg')),
		:university_profiles_attributes => 
		[
			{
			    :classification => 'Campus Site',
				:description => 'Lot 1, Baguio City Campus(Main)',
				:owner => 'UPB',
				:total_area_hectare => '3.0494',
				:total_area_meter => '30494',
				:acquisition => 'Proclamation No. 807, approved dated Dec. 18, 1961',
				:titling_status => 'P-3107',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Currently being utilized by the Main Campus',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot 3, Baguio City Campus(Near the lot of the Archbishop of Manila)',
				:owner => 'UPB',
				:total_area_hectare => '0.4887',
				:total_area_meter => '4887',
				:acquisition => 'Proclamation No. 352 approved dated March 31, 2004 with Special Patent No. 3658 dated June 23, 2004',
				:titling_status => 'P-3107',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Fenced off by the Archbishop of Manila Property',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Residential',
				:description => 'Lot A PSD-131102-001883, UP Baguio (near Walk-Up Appt.)',
				:owner => 'UPB',
				:total_area_hectare => '0.3298',
				:total_area_meter => '3298',
				:acquisition => 'Deed of Donation by GSIS in Mar. 23, 1992',
				:titling_status => 'T-58228',
				:date_issued => DateTime.new(1993,2,4),
				:tax_dec_no => '',
				:remarks => 'Currently being utilized for faculty/staff use.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Residential',
				:description => 'Lot B PSD-131102-001883, UP Baguio Residence Hall',
				:owner => 'UPB',
				:total_area_hectare => '0.9802',
				:total_area_meter => '9802',
				:acquisition => 'Deed of Donation by GSIS in Mar. 23, 1993',
				:titling_status => 'T-58229',
				:date_issued => DateTime.new(1993,2,4),
				:tax_dec_no => '',
				:remarks => 'Occupied by 17 family squatters and under court litigation for the correction of the technical description of the title.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot 3A2, SWO-40968, UP Baguio Campus (near Department of Tourism), Governor Pack Road, Baguio City',
				:owner => 'UPB',
				:total_area_hectare => '0.2132',
				:total_area_meter => '2132',
				:acquisition => 'Per DENR records, Lots 3A1 to 3 are UP properties',
				:titling_status => 'Untitled',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Planned to be transformed into eco-park.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Research',
				:description => 'Sabkil, Itogon, Benguet',
				:owner => 'UPB',
				:total_area_hectare => '2.0047',
				:total_area_meter => '20047',
				:acquisition => 'Deed of Absolute Sale dated Sept. 25, 1963',
				:titling_status => 'T-1964',
				:date_issued => DateTime.new(1963,10,25),
				:tax_dec_no => '',
				:remarks => 'Planted with trees and planned to be developed by the College of Science',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Research',
				:description => 'Sabkil, Itogon, Benguet',
				:owner => 'UPB',
				:total_area_hectare => '1.9044',
				:total_area_meter => '19044',
				:acquisition => 'Deed of Absolute Sale dated Sept. 25, 1963',
				:titling_status => 'T-1965',
				:date_issued => DateTime.new(1963,10,25),
				:tax_dec_no => '',
				:remarks => 'Planted with trees and planned to be developed by the College of Science',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
		]
	}
}
University.create!(params[:university])


uploader = ImageUploader.new
my_file = File.open(File.join(Rails.root, '/app/assets/images/up_mindanao.jpg'))
uploader.store!(my_file)
params =  
{ :university =>
	{
		:univ_name => 'UP Baguio',
		:image => File.open(File.join(Rails.root, '/app/assets/images/up_baguio.jpg')),
		:university_profiles_attributes => 
		[
			{
			    :classification => 'Campus Site',
				:description => 'Lot 1, Baguio City Campus(Main)',
				:owner => 'UPB',
				:total_area_hectare => '3.0494',
				:total_area_meter => '30494',
				:acquisition => 'Proclamation No. 807, approved dated Dec. 18, 1961',
				:titling_status => 'P-3107',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Currently being utilized by the Main Campus',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot 3, Baguio City Campus(Near the lot of the Archbishop of Manila)',
				:owner => 'UPB',
				:total_area_hectare => '0.4887',
				:total_area_meter => '4887',
				:acquisition => 'Proclamation No. 352 approved dated March 31, 2004 with Special Patent No. 3658 dated June 23, 2004',
				:titling_status => 'P-3107',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Fenced off by the Archbishop of Manila Property',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Residential',
				:description => 'Lot A PSD-131102-001883, UP Baguio (near Walk-Up Appt.)',
				:owner => 'UPB',
				:total_area_hectare => '0.3298',
				:total_area_meter => '3298',
				:acquisition => 'Deed of Donation by GSIS in Mar. 23, 1992',
				:titling_status => 'T-58228',
				:date_issued => DateTime.new(1993,2,4),
				:tax_dec_no => '',
				:remarks => 'Currently being utilized for faculty/staff use.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Residential',
				:description => 'Lot B PSD-131102-001883, UP Baguio Residence Hall',
				:owner => 'UPB',
				:total_area_hectare => '0.9802',
				:total_area_meter => '9802',
				:acquisition => 'Deed of Donation by GSIS in Mar. 23, 1993',
				:titling_status => 'T-58229',
				:date_issued => DateTime.new(1993,2,4),
				:tax_dec_no => '',
				:remarks => 'Occupied by 17 family squatters and under court litigation for the correction of the technical description of the title.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot 3A2, SWO-40968, UP Baguio Campus (near Department of Tourism), Governor Pack Road, Baguio City',
				:owner => 'UPB',
				:total_area_hectare => '0.2132',
				:total_area_meter => '2132',
				:acquisition => 'Per DENR records, Lots 3A1 to 3 are UP properties',
				:titling_status => 'Untitled',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Planned to be transformed into eco-park.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Research',
				:description => 'Sabkil, Itogon, Benguet',
				:owner => 'UPB',
				:total_area_hectare => '2.0047',
				:total_area_meter => '20047',
				:acquisition => 'Deed of Absolute Sale dated Sept. 25, 1963',
				:titling_status => 'T-1964',
				:date_issued => DateTime.new(1963,10,25),
				:tax_dec_no => '',
				:remarks => 'Planted with trees and planned to be developed by the College of Science',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Research',
				:description => 'Sabkil, Itogon, Benguet',
				:owner => 'UPB',
				:total_area_hectare => '1.9044',
				:total_area_meter => '19044',
				:acquisition => 'Deed of Absolute Sale dated Sept. 25, 1963',
				:titling_status => 'T-1965',
				:date_issued => DateTime.new(1963,10,25),
				:tax_dec_no => '',
				:remarks => 'Planted with trees and planned to be developed by the College of Science',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
		]
	}
}
University.create!(params[:university])


uploader = ImageUploader.new
my_file = File.open(File.join(Rails.root, '/app/assets/images/up_os.jpg'))
uploader.store!(my_file)
params =  
{ :university =>
	{
		:univ_name => 'UP Baguio',
		:image => File.open(File.join(Rails.root, '/app/assets/images/up_baguio.jpg')),
		:university_profiles_attributes => 
		[
			{
			    :classification => 'Campus Site',
				:description => 'Lot 1, Baguio City Campus(Main)',
				:owner => 'UPB',
				:total_area_hectare => '3.0494',
				:total_area_meter => '30494',
				:acquisition => 'Proclamation No. 807, approved dated Dec. 18, 1961',
				:titling_status => 'P-3107',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Currently being utilized by the Main Campus',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot 3, Baguio City Campus(Near the lot of the Archbishop of Manila)',
				:owner => 'UPB',
				:total_area_hectare => '0.4887',
				:total_area_meter => '4887',
				:acquisition => 'Proclamation No. 352 approved dated March 31, 2004 with Special Patent No. 3658 dated June 23, 2004',
				:titling_status => 'P-3107',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Fenced off by the Archbishop of Manila Property',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Residential',
				:description => 'Lot A PSD-131102-001883, UP Baguio (near Walk-Up Appt.)',
				:owner => 'UPB',
				:total_area_hectare => '0.3298',
				:total_area_meter => '3298',
				:acquisition => 'Deed of Donation by GSIS in Mar. 23, 1992',
				:titling_status => 'T-58228',
				:date_issued => DateTime.new(1993,2,4),
				:tax_dec_no => '',
				:remarks => 'Currently being utilized for faculty/staff use.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Residential',
				:description => 'Lot B PSD-131102-001883, UP Baguio Residence Hall',
				:owner => 'UPB',
				:total_area_hectare => '0.9802',
				:total_area_meter => '9802',
				:acquisition => 'Deed of Donation by GSIS in Mar. 23, 1993',
				:titling_status => 'T-58229',
				:date_issued => DateTime.new(1993,2,4),
				:tax_dec_no => '',
				:remarks => 'Occupied by 17 family squatters and under court litigation for the correction of the technical description of the title.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot 3A2, SWO-40968, UP Baguio Campus (near Department of Tourism), Governor Pack Road, Baguio City',
				:owner => 'UPB',
				:total_area_hectare => '0.2132',
				:total_area_meter => '2132',
				:acquisition => 'Per DENR records, Lots 3A1 to 3 are UP properties',
				:titling_status => 'Untitled',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Planned to be transformed into eco-park.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Research',
				:description => 'Sabkil, Itogon, Benguet',
				:owner => 'UPB',
				:total_area_hectare => '2.0047',
				:total_area_meter => '20047',
				:acquisition => 'Deed of Absolute Sale dated Sept. 25, 1963',
				:titling_status => 'T-1964',
				:date_issued => DateTime.new(1963,10,25),
				:tax_dec_no => '',
				:remarks => 'Planted with trees and planned to be developed by the College of Science',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Research',
				:description => 'Sabkil, Itogon, Benguet',
				:owner => 'UPB',
				:total_area_hectare => '1.9044',
				:total_area_meter => '19044',
				:acquisition => 'Deed of Absolute Sale dated Sept. 25, 1963',
				:titling_status => 'T-1965',
				:date_issued => DateTime.new(1963,10,25),
				:tax_dec_no => '',
				:remarks => 'Planted with trees and planned to be developed by the College of Science',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
		]
	}
}
University.create!(params[:university])


uploader = ImageUploader.new
my_file = File.open(File.join(Rails.root, '/app/assets/images/up_system.jpg'))
uploader.store!(my_file)
params =  
{ :university =>
	{
		:univ_name => 'UP Baguio',
		:image => File.open(File.join(Rails.root, '/app/assets/images/up_baguio.jpg')),
		:university_profiles_attributes => 
		[
			{
			    :classification => 'Campus Site',
				:description => 'Lot 1, Baguio City Campus(Main)',
				:owner => 'UPB',
				:total_area_hectare => '3.0494',
				:total_area_meter => '30494',
				:acquisition => 'Proclamation No. 807, approved dated Dec. 18, 1961',
				:titling_status => 'P-3107',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Currently being utilized by the Main Campus',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot 3, Baguio City Campus(Near the lot of the Archbishop of Manila)',
				:owner => 'UPB',
				:total_area_hectare => '0.4887',
				:total_area_meter => '4887',
				:acquisition => 'Proclamation No. 352 approved dated March 31, 2004 with Special Patent No. 3658 dated June 23, 2004',
				:titling_status => 'P-3107',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Fenced off by the Archbishop of Manila Property',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Residential',
				:description => 'Lot A PSD-131102-001883, UP Baguio (near Walk-Up Appt.)',
				:owner => 'UPB',
				:total_area_hectare => '0.3298',
				:total_area_meter => '3298',
				:acquisition => 'Deed of Donation by GSIS in Mar. 23, 1992',
				:titling_status => 'T-58228',
				:date_issued => DateTime.new(1993,2,4),
				:tax_dec_no => '',
				:remarks => 'Currently being utilized for faculty/staff use.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Residential',
				:description => 'Lot B PSD-131102-001883, UP Baguio Residence Hall',
				:owner => 'UPB',
				:total_area_hectare => '0.9802',
				:total_area_meter => '9802',
				:acquisition => 'Deed of Donation by GSIS in Mar. 23, 1993',
				:titling_status => 'T-58229',
				:date_issued => DateTime.new(1993,2,4),
				:tax_dec_no => '',
				:remarks => 'Occupied by 17 family squatters and under court litigation for the correction of the technical description of the title.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot 3A2, SWO-40968, UP Baguio Campus (near Department of Tourism), Governor Pack Road, Baguio City',
				:owner => 'UPB',
				:total_area_hectare => '0.2132',
				:total_area_meter => '2132',
				:acquisition => 'Per DENR records, Lots 3A1 to 3 are UP properties',
				:titling_status => 'Untitled',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Planned to be transformed into eco-park.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Research',
				:description => 'Sabkil, Itogon, Benguet',
				:owner => 'UPB',
				:total_area_hectare => '2.0047',
				:total_area_meter => '20047',
				:acquisition => 'Deed of Absolute Sale dated Sept. 25, 1963',
				:titling_status => 'T-1964',
				:date_issued => DateTime.new(1963,10,25),
				:tax_dec_no => '',
				:remarks => 'Planted with trees and planned to be developed by the College of Science',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Research',
				:description => 'Sabkil, Itogon, Benguet',
				:owner => 'UPB',
				:total_area_hectare => '1.9044',
				:total_area_meter => '19044',
				:acquisition => 'Deed of Absolute Sale dated Sept. 25, 1963',
				:titling_status => 'T-1965',
				:date_issued => DateTime.new(1963,10,25),
				:tax_dec_no => '',
				:remarks => 'Planted with trees and planned to be developed by the College of Science',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
		]
	}
}
University.create!(params[:university])


uploader = ImageUploader.new
my_file = File.open(File.join(Rails.root, '/app/assets/images/up_visayas.jpg'))
uploader.store!(my_file)
params =  
{ :university =>
	{
		:univ_name => 'UP Baguio',
		:image => File.open(File.join(Rails.root, '/app/assets/images/up_baguio.jpg')),
		:university_profiles_attributes => 
		[
			{
			    :classification => 'Campus Site',
				:description => 'Lot 1, Baguio City Campus(Main)',
				:owner => 'UPB',
				:total_area_hectare => '3.0494',
				:total_area_meter => '30494',
				:acquisition => 'Proclamation No. 807, approved dated Dec. 18, 1961',
				:titling_status => 'P-3107',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Currently being utilized by the Main Campus',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot 3, Baguio City Campus(Near the lot of the Archbishop of Manila)',
				:owner => 'UPB',
				:total_area_hectare => '0.4887',
				:total_area_meter => '4887',
				:acquisition => 'Proclamation No. 352 approved dated March 31, 2004 with Special Patent No. 3658 dated June 23, 2004',
				:titling_status => 'P-3107',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Fenced off by the Archbishop of Manila Property',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Residential',
				:description => 'Lot A PSD-131102-001883, UP Baguio (near Walk-Up Appt.)',
				:owner => 'UPB',
				:total_area_hectare => '0.3298',
				:total_area_meter => '3298',
				:acquisition => 'Deed of Donation by GSIS in Mar. 23, 1992',
				:titling_status => 'T-58228',
				:date_issued => DateTime.new(1993,2,4),
				:tax_dec_no => '',
				:remarks => 'Currently being utilized for faculty/staff use.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Residential',
				:description => 'Lot B PSD-131102-001883, UP Baguio Residence Hall',
				:owner => 'UPB',
				:total_area_hectare => '0.9802',
				:total_area_meter => '9802',
				:acquisition => 'Deed of Donation by GSIS in Mar. 23, 1993',
				:titling_status => 'T-58229',
				:date_issued => DateTime.new(1993,2,4),
				:tax_dec_no => '',
				:remarks => 'Occupied by 17 family squatters and under court litigation for the correction of the technical description of the title.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Campus Site',
				:description => 'Lot 3A2, SWO-40968, UP Baguio Campus (near Department of Tourism), Governor Pack Road, Baguio City',
				:owner => 'UPB',
				:total_area_hectare => '0.2132',
				:total_area_meter => '2132',
				:acquisition => 'Per DENR records, Lots 3A1 to 3 are UP properties',
				:titling_status => 'Untitled',
				:date_issued => '',
				:tax_dec_no => '',
				:remarks => 'Planned to be transformed into eco-park.',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Research',
				:description => 'Sabkil, Itogon, Benguet',
				:owner => 'UPB',
				:total_area_hectare => '2.0047',
				:total_area_meter => '20047',
				:acquisition => 'Deed of Absolute Sale dated Sept. 25, 1963',
				:titling_status => 'T-1964',
				:date_issued => DateTime.new(1963,10,25),
				:tax_dec_no => '',
				:remarks => 'Planted with trees and planned to be developed by the College of Science',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
			{
				:classification => 'Research',
				:description => 'Sabkil, Itogon, Benguet',
				:owner => 'UPB',
				:total_area_hectare => '1.9044',
				:total_area_meter => '19044',
				:acquisition => 'Deed of Absolute Sale dated Sept. 25, 1963',
				:titling_status => 'T-1965',
				:date_issued => DateTime.new(1963,10,25),
				:tax_dec_no => '',
				:remarks => 'Planted with trees and planned to be developed by the College of Science',
				:titling_step_eins => '',
				:titling_step_zwei => '',
				:titling_step_drei => '',
				:titling_step_vier => '',
				:titling_step_funf => '',
				:titling_step_sechs => '',
				:titling_step_sieben => '',
				:titling_step_acht => '',
				:titling_step_neun => '',
				:titling_step_zehn => '',
				},
		]
	}
}
University.create!(params[:university])


